name: poker-deployment

env:
  "S3_BUCKET_NAME": "poker-deployment"
  "EBS_APPLICATION_NAME": "Planning poker"
  "EBS_ENVIRONMENT_NAME": "Planningpoker-env"
  "AWS_REGION": "us-east-1"
  "DEPLOY_PACKAGE_NAME": "poker-deployment-${{github.sha}}.zip"
  "working-directory": "./backend"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Build the application
        run: |
          npm install
          npm run build
        working-directory: ${{env.working-directory}}
      - name: Zip the application
        run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
        working-directory: ${{env.working-directory}}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}
      - name: Upload to S3
        run: aws s3 cp ${{env.DEPLOY_PACKAGE_NAME}} s3://${{env.S3_BUCKET_NAME}}/
        working-directory: ${{env.working-directory}}
      - name: Create new application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{env.EBS_APPLICATION_NAME}} \
            --source-bundle S3Bucket=${{env.S3_BUCKET_NAME}},S3Key=${{env.DEPLOY_PACKAGE_NAME}} \
            --version-label "ver-${{github.sha}}" \
            --description "commit-sha-${{github.sha}}"
      - name: Deploy new version
        run: aws elasticbeanstalk update-environment --environment-name ${{env.EBS_ENVIRONMENT_NAME}} --version-label "ver-${{github.sha}}"
      - name: Print success message on completion
        run: echo "Deployment successful"
