name: Deploy frontend to S3

env:
  AWS_REGION: eu-west-2
  S3_BUCKET_NAME: "planning-poker-prod-frontend"
  WORKING_DIRECTORY: "./frontend"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Build frontend
        run: |
          rm .env
          mv .env.production .env
          yarn install
          yarn build
          aws s3 cp out s3://${{ env.S3_BUCKET_NAME }} --recursive
        working-directory: ${{ env.WORKING_DIRECTORY }}
